apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subsets: []
